### ISSUE TITLE
Question about where to look

### ISSUE THREAD

**Issue by sirtthe9th** [AllenMattson/VBA#1]
Hi, does anyone know if there is a module in here that could be used to help make an appointment tracker? My gf works at a nail salon and they want to keep track of appointments using Excel. So they need to be able to input certain criteria such as name, date, phone number, etc and then be able to visualize the appointments for a certain date range. 

I figured I'd ask to see if I can get a bit of a head start instead of randomly looking through it.

Thanks, Thomas Reid

**Comment by AllenMattson** [comment]
Hey there, I don't have a specific example for this issue. There should be some examples to help you, otherwise share some details on the project and I'll be happy to add code which may help. If it's outlook code you're in need of I recommend the book outlook 2000 programming. It's old but it has everything.

**Comment by sirtthe9th** [comment]
Hi Allen,

Thanks for the response, I'll check out the book.

Thanks, Thomas Reid

**Comment by colonelxy-zz** [comment]
Hi Thomas,

I would use a calendar for that, She could easily slightly transform the
attached to suit her needs. And it keeps the records through the years,

Thanks & Regards,


Harold



"If you learn only methods, you'll be tied to your
methods, but if you learn principles you can devise your own methods."
― Ralph Waldo Emerson





Le mar. 22 sept. 2020, à 23 h 52, sirtthe9th <notifications@github.com> a
écrit :

**Comment by sirtthe9th** [comment]
Hi Harold,

Now that you say that, I'm amazed we didn't think of that first! I guess when we first started talking about it, she had suggested using Excel in some way, so I just started brainstorming ways to use Excel. 

Nice addition with the quote as well. Thanks for your input!

Thanks, Thomas Reid

**Comment by colonelxy-zz** [comment]
😐😑😄

Thanks & Regards,


Harold



"If you learn only methods, you'll be tied to your
methods, but if you learn principles you can devise your own methods."
― Ralph Waldo Emerson





Le mer. 23 sept. 2020, à 17 h 53, sirtthe9th <notifications@github.com> a
écrit :
